---
title: "Homework 5"
author: "Shane"
date: '`r format(Sys.time(), "%Y-%m-%d")`'
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggridges)
library(patchwork)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```



# Problem 1

## import data

```{r}
homicide_df = 
  read_csv("data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved",
    )
  ) %>% 
  select(city_state, resolved) %>% 
  filter(city_state != "Tulsa_AL")
```

## aggregate origin data

```{r}
homicide_sum = 
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

## test on one data

```{r}
prop.test(
  homicide_sum %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved), 
  homicide_sum %>% filter(city_state == "Baltimore_MD") %>% pull(hom_total)
) %>% 
  broom::tidy() %>% 
  select(estimate, conf.low, conf.high) %>% 
  knitr::kable()
```

## write function

```{r}
prop_test = function(x){
  
  test = prop.test(
    homicide_sum %>% filter(city_state == x) %>% pull(hom_unsolved), 
    homicide_sum %>% filter(city_state == x) %>% pull(hom_total)
  ) %>% 
  broom::tidy() %>% 
  select(estimate, conf.low, conf.high) 
  
}
```

## function applied

```{r}
city_prop_test = 
  map(.x = homicide_sum$city_state, .f = ~prop_test(.x)) %>% 
  bind_rows() %>% 
  mutate(city_state = homicide_sum$city_state) %>% 
  select(city_state, everything())
```

## making plot

```{r}
city_prop_test %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```



# Problem 2

## get name 

```{r}
file_name = list.files("data/study_data")
```

## import data

```{r}
data = 
  map(.x = str_c("data/study_data/", file_name),~read_csv(.x)) %>% 
  bind_rows() %>% 
  mutate(name = file_name) %>% 
  select(name, everything()) %>% 
  separate(name, c("arm", "arm_id", "end")) %>% 
  unite(group, c("arm", "arm_id"), remove = FALSE) %>% 
  select(!"end") %>% 
  pivot_longer(
    "week_1":"week_8", 
    names_to = "week", 
    values_to = "observation", 
    names_prefix = "week_"
  ) %>% 
  mutate(
    arm_id = as.numeric(arm_id),
    week = as.numeric(week)   
  )
``` 




  













